Migrate
stepa1000/my-web-server pull request #11
Opened 2023-04-06 10:19 UTC by stepa1000

2023-04-06 11:26 UTC, pavelzarubin commented
Это никуда не годится. Что будешь делать если, понадобится изменить бд? Сносить ее всю и вручную заполнять? Миграции мы задаем с помощью sql файлов. Из кода мы их просто считываем и запускаем, а в бд обычно хранится история версий, чтобы одни и те же миграции при перезапуске не запускать.

2023-04-07 07:10 UTC, stepa1000 commented
beam-migrate, вроде предаставляет весь вункционал для миграций. Но если надо через sql файл то попробую через него.

2023-04-07 08:03 UTC, pavelzarubin commented
ну даже если так, изменять миграции внутри кода неудобно. Потом будешь скакать по коммитам, чтобы искать косяки

2023-04-07 09:57 UTC, stepa1000 commented
beam-migrate безапасен на уравне типов. Я смотрел пример в статье https://www.williamyaoh.com/posts/2019-09-27-figuring-out-beam-migrations.html . Но как хатите.

2023-04-07 10:15 UTC, stepa1000 commented
я нашол библиотеку для чтения sql файла https://hackage.haskell.org/package/postgresql-simple-0.6.5/docs/Database-PostgreSQL-Simple.html, но в зависимостях postgresql-simple. А в условиях написанно что лучше на beam.

2023-04-11 06:45 UTC, pavelzarubin requested changes

2023-04-11 06:45 UTC, pavelzarubin commented on sql-migration/initialMigration.sql
> +    "category" TEXT NOT NULL,
таблицы для категорий нет, смотри требования к проекту

2023-04-11 06:45 UTC, pavelzarubin commented on src/Data/Config.hs
> +  defaultConnectInfo {connectUser = "stepan", connectDatabase = "newsdb", connectPassword = "123"}
эта функция лишния

2023-04-17 11:31 UTC, pavelzarubin requested changes

2023-04-17 11:31 UTC, pavelzarubin commented on src/Data/Imp/Database.hs
> +      _categoryParent = undefined,
undefined мы не используем

2023-04-17 11:31 UTC, pavelzarubin commented on src/Data/Imp/Migration.hs
> +      f "d_addCategoryNews.sql"
а давай ты просто переименуешь файлы, например `01_create_user.sql`, и просто считывай список файлов и прогоняй его

2023-04-17 11:31 UTC, pavelzarubin commented on sql-migration/d_addCategoryNews.sql
> +    "child" TEXT[],
а зачем хранить список производных категорий?

2023-04-17 11:31 UTC, pavelzarubin commented on src/Data/Imp/Server/Category.hs
> +{-
лишние комментарии

2023-04-17 11:31 UTC, pavelzarubin commented on sql-migration/b_create_news.sql
> +  ( "newsName" TEXT NOT NULL UNIQUE,
почему не используешь Id для новостей, категорий и пользователей?

2023-04-17 11:31 UTC, pavelzarubin commented on sql-migration/d_addCategoryNews.sql
> +    "parent" TEXT NOT NULL,
почему родительская категория не может быть пустой? Ведь могут быть категории без родителей

2023-04-18 04:34 UTC, stepa1000 commented on src/Data/Imp/Database.hs
> +      _categoryParent = undefined,
с undefined пишуться некоторые запросы в beam. Например:
```haskell
l <- listStreamingRunSelect c $ lookup_ (dbCategory webServerDB) (primaryKey $ categoryName ca)
``` 
lookup_ требует указать данные по каки полям искать в какой структуре. Для этого создаёться функция заполняющая только те поля которые нужно.

2023-04-18 04:51 UTC, stepa1000 commented on sql-migration/d_addCategoryNews.sql
> +    "child" TEXT[],
Для полноты, чтобы для любого названия катигории можно было получить и у предков и у дочерниие категории. 

Конечно достаточно указать только радителей, но я не знаю как работает алгоритм поиска в postgrase, и будет ли еффективно по предкам.

2023-04-18 04:54 UTC, stepa1000 commented on sql-migration/b_create_news.sql
> +  ( "newsName" TEXT NOT NULL UNIQUE,
Нет в функциональных требованиях к пректу.

2023-04-18 05:00 UTC, pavelzarubin commented on sql-migration/b_create_news.sql
> +  ( "newsName" TEXT NOT NULL UNIQUE,
У категорий есть.
К тому же заголовки вполне могут быть неуникальными. Потому нужно использовать Id

2023-04-18 05:03 UTC, stepa1000 commented on sql-migration/d_addCategoryNews.sql
> +    "parent" TEXT NOT NULL,
потамучто я подумал что только у одной категории может отсутствовать предок, это категория General, и как исключения у неё предок пустая строка.  

Но так как к описанию проекта нет каких либо услови к тому в каком ввиде должна быть категория, то можно работать с бесвязанными.

Хотя я считаю удобным иметь категорию General чтоб было возможно построить дерево из категорий и отпрвить пользователю, или работать с целым дерево или потдеревом в коде.

2023-04-18 05:29 UTC, pavelzarubin commented on src/Data/Imp/Database.hs
> +      _categoryParent = undefined,
Я с одной стороны не против. Но лучше на мой взгляд использовать какие-либо нейтральные значения, они все равно будут проигнорированы. Ну и в требованиях также есть пометка, что undefined нельзя использовать.

2023-04-18 09:14 UTC, stepa1000 commented on sql-migration/b_create_news.sql
> +  ( "newsName" TEXT NOT NULL UNIQUE,
а имя категорий уникально?

2023-04-18 09:35 UTC, pavelzarubin commented on sql-migration/b_create_news.sql
> +  ( "newsName" TEXT NOT NULL UNIQUE,
Ну да. Ну типа у нас может быть куча новостей, например `Победа в чемпионате`. но две разные категории `спорт` быть не могут

2023-05-03 09:10 UTC, pavelzarubin requested changes

2023-05-03 09:10 UTC, pavelzarubin commented on src/Data/Imp/Database.hs
> +  { _categoryUuidCategory :: Columnar f UUID,
у тебя в миграции отсутствует поле uuid

2023-05-03 09:10 UTC, pavelzarubin commented on src/Data/Imp/Migration.hs
> +  c <- connect ci
Исправь имена на более развернутые. Это касается всех файлов.

2023-05-03 09:10 UTC, pavelzarubin commented on src/Data/Imp/Server/News.hs
> +filterFlagPublished _ _ _ = val_ True -- ????????????????????????????
????????

2023-05-03 13:09 UTC, stepa1000 commented on src/Data/Imp/Server/News.hs
> +filterFlagPublished _ _ _ = val_ True -- ????????????????????????????
Я сомниваюсь в коррекности работы программы из-за того что флаг для публикации новостей лучше бы было передовать без Maybe, тоесть задовать значение по умолчанию при поиске в API сервера.

2023-05-03 13:15 UTC, stepa1000 commented on src/Data/Imp/Server/News.hs
> +filterFlagPublished _ _ _ = val_ True -- ????????????????????????????
Но менять логику поиска и менять структуру получения данных от клиента на новую структуру с единственным полем без Maybe слишком трудно.

2023-05-03 13:42 UTC, stepa1000 commented on src/Data/Imp/Migration.hs
> +  c <- connect ci
Имена sql файлов пронумированны и имеют подробное название. Остальные файлы разбиты на три категории API от серванта, фаил Web.hs, абстракный интерыейс в папке Control, и имплементация в папке Data. 

В Control модуль сервера зависит от модулей в паке сервера, они названы по имени соответствующих данных функционал с которыми имеют.  Логгер лежит вместе с сервером так как не имеет зависимостей. Сервер имеет своё название так-как агриагирует подсистемы работы с клиентом.

Data: в папке Imp реализуеться выше написанное в монаде IO, имплементаций под другии монады покачто нет.  Логгер находиться отдельно так-как скопировал с проекта эхо-бота. Модули не имеющих листьев лежат сверху. 

Единственное что я бы сейчас хотел бы поменять так это поместить имеющиеся модули с типами в одну одноимённую папку, чтоб сразу было ясно что-где распалогаеться. Конфиг, утилиты, инстанци можно оставить на верху ибо выполняют разные задачи.

2023-05-04 03:21 UTC, pavelzarubin commented on src/Data/Imp/Migration.hs
> +  c <- connect ci
Я про имена переменных и функций, с файлами все ок. Имена типа `c`, `ci`, `lcnfp` не отражают суть того, за что отвечают.

2023-05-15 07:02 UTC, pavelzarubin approved these changes

2023-05-15 07:02 UTC, pavelzarubin commented on src/Data/Imp/Server.hs
> +  liftIO $ Logger.logError (Server.handleLogger hServer) "createNewsEddit: parametors not just"
parameters are null

2023-05-16 04:23 UTC, merged