Revert "Migrate"
stepa1000/my-web-server pull request #13
Opened 2023-05-24 09:28 UTC by stepa1000

Reverts stepa1000/my-web-server#11

#12

2023-06-01 04:55 UTC, pavelzarubin requested changes
На чистой БД не запускается.
![Снимок экрана от 2023-06-01 07-54-31](https://github.com/stepa1000/my-web-server/assets/98732727/081fdea2-a889-4263-ae69-295173821956)

2023-06-01 08:24 UTC, pavelzarubin commented
А по поводу тестов я уже говорил. Тебе не нужно тестировать взаимодействие с базой. Тебе нужно тестировать только логику.

2023-06-01 09:27 UTC, pavelzarubin commented
Тесты так и остались сломанными

2023-06-02 03:30 UTC, pavelzarubin commented
![Снимок экрана от 2023-06-02 06-29-39](https://github.com/stepa1000/my-web-server/assets/98732727/08e4a4ac-8299-451c-900d-7a757aef1d11)
у меня тесты не собираются вообще

2023-06-02 07:37 UTC, pavelzarubin commented
так, сейчас что-то заработало
у тебя тут еще есть проблема с таблицей пользователей
переименуй `user` -> `users`, а то psql и прочие путают твою таблицу, с таблицей пользователей базы

2023-06-13 06:45 UTC, pavelzarubin commented
а ты тесты собирал? У тебя там очень много варнингов, конфликтов и есть ошибки. Перепроверь их.

2023-06-14 05:19 UTC, pavelzarubin requested changes

2023-06-14 05:19 UTC, pavelzarubin commented on test/AuthorizationSpec.hs
> -    checkUser = fromRight undefined $ stateExeT stateAuth $ do
я конеечно понимаю, что undefined проигнорируется, но давай без него

2023-06-14 05:19 UTC, pavelzarubin commented on test/Imp/Pure/Authorization.hs
> +pureUserList :: OffSet -> Limit -> StateAuthorization [UserPublic]
а тебе здесь точно нужен State? Ты же по сути возвращаешь значение, а потом в тестах этот State распаковываешь

2023-06-14 05:28 UTC, pavelzarubin commented
По тестам в текущий момент все ок. Но у тебя в некоторых местах логики недостаточно. Например нет проверки, что пользователь с таким логином уже существует, нет обработки ошибки при создании одинаковых категорий.

2023-06-14 05:29 UTC, pavelzarubin commented on app/Main.hs
> +  server actExit 5432 conf
так этот порт должен быть в конфиге. А то курлы не работают, да и это стандартный порт postgresql, сервер просто не запустится.

2023-06-14 05:40 UTC, stepa1000 commented on test/Imp/Pure/Authorization.hs
> +pureUserList :: OffSet -> Limit -> StateAuthorization [UserPublic]
Требуеться проверить вывод списка пользователей при возможности добавлении аккаунтов. 

Состояние нужно чтобы хранить чистую БД ввиде Map и передовать состояние проверяемого значения между разными функциями в обработчике, так что при отсутствие монады, добавление пользователя и проверка состояния БД будет невозможна.

2023-06-14 06:23 UTC, pavelzarubin requested changes

2023-06-14 06:23 UTC, pavelzarubin commented on app/Main.hs
> +  server actExit (fromIntegral $ connectPort $ confConnectionInfo conf) conf
Не не, тут нужен отдельный порт, для запросов на сервер, а не порт для базы данных. Запусти и проверь.

2023-06-14 06:28 UTC, pavelzarubin commented on test/Imp/Pure/Authorization.hs
> +pureUserList :: OffSet -> Limit -> StateAuthorization [UserPublic]
А зачем тебе тестировать две разные логики? Достаточно просто возвращать список пользователей. Тебе же юнит тесты нужны, а не проверять совместную работу.

2023-06-14 09:18 UTC, pavelzarubin approved these changes

2023-06-14 09:48 UTC, merged