added login to account checking the unique.
stepa1000/my-web-server pull request #16
Opened 2023-06-15 07:55 UTC by stepa1000

#15

2023-06-19 09:08 UTC, pavelzarubin approved these changes

2023-06-19 09:10 UTC, pavelzarubin requested changes

2023-06-19 09:10 UTC, pavelzarubin commented on src/Control/Server.hs
> +      vUser <- ServerAuthorization.handleCreateUserCheck (handleAuthorization hServer) name login password flagMakeNews flagAdmin
имя функции можно было и не менять

2023-06-21 03:59 UTC, pavelzarubin commented on src/Control/Server/Authorization.hs
> +  handleCreateUserCheck auth login login password flagMNews True
у тебя админ при первом запуске не создается

2023-06-21 05:28 UTC, stepa1000 commented
База данных крашиться при проверке уникальность ввода.

2023-06-21 05:32 UTC, pavelzarubin commented
> База данных крашиться при проверке уникальность ввода.
> 
> `newsdb=# RAISE LOG unique_violation;
> 
> ERROR: syntax error at or near "RAISE" LINE 1: RAISE LOG unique_violation; ^ newsdb=# RAISE; ERROR: syntax error at or near "RAISE" LINE 1: RAISE; ^ newsdb=# ereport(LOG, errcode(unique_violation), errmsg("unique violation")); ERROR: syntax error at or near "ereport" LINE 1: ereport(LOG, ^ newsdb=# newsdb=# newsdb=# newsdb=# ereport(LOG, errcode(unique_violation), errmsg("unique violation")); ERROR: syntax error at or near "ereport" LINE 1: ereport(LOG, ^ newsdb=# ; newsdb=# newsdb=# restart_after_crash true newsdb-# ;`

а зачем тебе что-то через psql проверять?

2023-06-21 05:40 UTC, pavelzarubin commented
у тебя создание админа не в миграции отражено. Потому админ типа создается при каждом запуске. Вот все и крашится.

2023-06-21 05:41 UTC, stepa1000 commented
> > База данных крашиться при проверке уникальность ввода.
> > `newsdb=# RAISE LOG unique_violation;
> > ERROR: syntax error at or near "RAISE" LINE 1: RAISE LOG unique_violation; ^ newsdb=# RAISE; ERROR: syntax error at or near "RAISE" LINE 1: RAISE; ^ newsdb=# ereport(LOG, errcode(unique_violation), errmsg("unique violation")); ERROR: syntax error at or near "ereport" LINE 1: ereport(LOG, ^ newsdb=# newsdb=# newsdb=# newsdb=# ereport(LOG, errcode(unique_violation), errmsg("unique violation")); ERROR: syntax error at or near "ereport" LINE 1: ereport(LOG, ^ newsdb=# ; newsdb=# newsdb=# restart_after_crash true newsdb-# ;`
> 
> а зачем тебе что-то через psql проверять?

У меня база данных крашиться при создании пользователя с имеющимся в базе данных логгином или с одинаковыми именами категорий. Пытался решить через psql ибо ошибка со стороны базы данных.

2023-06-21 05:44 UTC, stepa1000 commented on src/Control/Server/Authorization.hs
> +  checkAccount <- handleAccountCheck auth login
Ошибка приводит к падению базы данных.

2023-06-21 06:30 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +    BPC.runInsert connectDB $
ну правильно крашится, `runInsert` возвращает число строк, а не номер ошибки. Ошибку нужно перехватывать.

2023-06-22 03:36 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
странное решение. Почему ты просто не можешь исключение перехватить и обработать? Зачем все усложнять?

2023-06-22 05:14 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Beam использует MonadFail. Из-за чего пришлось написать сопственный коннект к базе данных, для того чтобы достать ошибку, избежав падения программы.

2023-06-22 05:32 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Интересно. Значит где-то внутри он все таки использует исключения, тк такой код сработал.
```
hCreateUser :: Logger.Handle IO -> Connection -> Name -> Login -> Password -> FlagMakeNews -> FlagAdmin -> IO UserPublic
hCreateUser logger connectDB name login password flagMNews flagAdmin = do
  Logger.logInfo logger "Create user"
  (UTCTime day _) <- getCurrentTime
  catch
    ( void $
        BPC.runInsert connectDB $
          insert (dbUser webServerDB) $
            insertValues
              [ UserT
                  { _userName = name,
                    _userLogin = login,
                    _userPasswordHash = getHash password,
                    _userDateCreation = day,
                    _userAdmin = flagAdmin,
                    _userMakeNews = flagMNews
                  }
              ]
    )
    handler
  --when (errorSQL == 23505) $ Logger.logWarning logger $ "Unique violation for: " Logger..< login
  return $
    UserPublic
      { nameUser = name,
        loginUser = login,
        dateCreationUser = day,
        adminUser = flagAdmin,
        makeNewsUser = flagMNews
      }
  where
    handler :: SqlError -> IO ()
    handler exc = do
      Logger.logWarning logger $ "Unique violation for: " Logger..< login
      Logger.logError logger $ "Exception: " <> (Data.Text.pack . show $ sqlState exc)
      return ()
```

2023-06-22 05:37 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
А ну да, ты используешь `runInsert` из `Database.Beam.Postgres.Conduit`, У `runInsert` под капотом использует `postgresql-simple`, потому и получается исключение словить

2023-06-22 06:50 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
https://github.com/stepa1000/beam/blob/59bed8032f7b006f115389fae4124913be61dd73/beam-postgres/Database/Beam/Postgres/Conduit.hs#LL104C1-L133C1

2023-06-22 07:04 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
а можешь подробнее расписать, как ты поймал краш бд? 
а то я как не пытался, ничего подобного не ловил

2023-06-22 07:34 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
> Beam использует MonadFail. Из-за чего пришлось написать сопственный коннект к базе данных, для того чтобы достать ошибку, избежав падения программы.

Fail нельзя поймать, так что я выевл строку скопировав функцию и стерев fail.

Я склонировал репозиторий beam и добавил функцию runInsertWithError, так-как использовать Internal можно только в библиотеке, так-как нужны функции и конструкторы из имплементации beam и postgresql-simple, для написания сопственного коннекта. Предоставляемые способы потключения либо используют fail для запросов к базе данных, либо игнорируют ошибки при исполнении.

2023-06-22 07:56 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Я имел в виду, до вот этих изменений.

2023-06-22 08:00 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Haskell fail скорее всего в stdin печатает, так как смог увидеть.

2023-06-22 08:31 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
А ты что делал? Просто пытался пользователя создать и сразу же соединение с базой терялось?

2023-06-22 08:37 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Да, пытался сосдать админа при инициализации.

2023-06-22 08:40 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Просто у тебя админ должен создаваться в миграции, а не отдельным запросом при запуске.

2023-06-22 08:53 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
https://github.com/stepa1000/my-web-server/pull/16#discussion_r1233755443

"достаточно объявить поле логина уникальным, а при создании отлавливать ошибку, что строка с таким логином уже есть."

2023-06-22 10:07 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
https://github.com/stepa1000/beam/blob/59bed8032f7b006f115389fae4124913be61dd73/beam-postgres/Database/Beam/Postgres/Conduit.hs#LL262C19-L262C19

Строка в которой вызываеться исключения, как видно по строкам выше при дисканекте с БД. Дисканекта нет и не отлавливалось.

https://github.com/stepa1000/beam/blob/59bed8032f7b006f115389fae4124913be61dd73/beam-postgres/Database/Beam/Postgres/Conduit.hs#L276

Строка в которй вызываеться ошибка со стороны psql, и следующей вызывался fail, после програма падала. Что и было отловленно.

Если не понятно, то пажалуйста заново распешите вопрос подробнее, а то я уже незнаю что еще добавить.

2023-06-22 10:37 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Можно упростить вызывая функцию errorMessage перед runInsert, но тайп чекер жалуеться на соеденения с БД . Можно сделать внутри моего соединения.

2023-06-22 10:54 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Нельзя.

https://github.com/stepa1000/beam/blob/59bed8032f7b006f115389fae4124913be61dd73/beam-postgres/Database/Beam/Postgres/Conduit.hs#L113

Чтобы вызвать errorMessage нужен обработчик соединения.

https://github.com/stepa1000/beam/blob/59bed8032f7b006f115389fae4124913be61dd73/beam-postgres/Database/Beam/Postgres/Conduit.hs#L120

После чего вызов исключения при потере соединения. Не происходило.

https://github.com/stepa1000/beam/blob/59bed8032f7b006f115389fae4124913be61dd73/beam-postgres/Database/Beam/Postgres/Conduit.hs#L130

После чего ловля ошибок при обработке запроса в БД.

Если имеються вопросы распешите подробнее пажалуйста.

2023-06-22 10:57 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
> А ты что делал? Просто пытался пользователя создать и сразу же соединение с базой терялось?

Соединение с базой не терялось.

2023-06-22 10:58 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
> Интересно. Значит где-то внутри он все таки использует исключения, так как такой код сработал.
> 
> ```
> hCreateUser :: Logger.Handle IO -> Connection -> Name -> Login -> Password -> FlagMakeNews -> FlagAdmin -> IO UserPublic
> hCreateUser logger connectDB name login password flagMNews flagAdmin = do
>   Logger.logInfo logger "Create user"
>   (UTCTime day _) <- getCurrentTime
>   catch
>     ( void $
>         BPC.runInsert connectDB $
>           insert (dbUser webServerDB) $
>             insertValues
>               [ UserT
>                   { _userName = name,
>                     _userLogin = login,
>                     _userPasswordHash = getHash password,
>                     _userDateCreation = day,
>                     _userAdmin = flagAdmin,
>                     _userMakeNews = flagMNews
>                   }
>               ]
>     )
>     handler
>   --when (errorSQL == 23505) $ Logger.logWarning logger $ "Unique violation for: " Logger..< login
>   return $
>     UserPublic
>       { nameUser = name,
>         loginUser = login,
>         dateCreationUser = day,
>         adminUser = flagAdmin,
>         makeNewsUser = flagMNews
>       }
>   where
>     handler :: SqlError -> IO ()
>     handler exc = do
>       Logger.logWarning logger $ "Unique violation for: " Logger..< login
>       Logger.logError logger $ "Exception: " <> (Data.Text.pack . show $ sqlState exc)
>       return ()
> ```

Исключение только при дисканекте, чего не было.

2023-06-22 10:59 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
> А ну да, ты используешь `runInsert` из `Database.Beam.Postgres.Conduit`, У `runInsert` под капотом использует `postgresql-simple`, потому и получается исключение словить

Используеться postgrasql-libpq

2023-06-22 11:01 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
> странное решение. Почему ты просто не можешь исключение перехватить и обработать? Зачем все усложнять?

Внутри runInsert исключения не обрабатываються.

2023-06-22 11:17 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      runInsertWithError connectDB $
Ну так все правильно. Внутри `runInsert` используется `execute_`. Он и бросает исключение. Исключение я обработал самостоятельно в своем коде. И как ты видишь, я обрабатываю только исключения которые возвращает база. Потерю соединения я не обрабатывал. Я хотел показать, что перехватить исключение, связанное с повторяющимися значениями, возможно и без форка beam. 
Собственно я вносил правки в прошлый коммит, а не в этот.

2023-06-26 09:05 UTC, pavelzarubin requested changes

2023-06-27 03:57 UTC, pavelzarubin requested changes

2023-06-27 03:57 UTC, pavelzarubin commented on scripts/curls/userCreate.sh
> -curl  -u "tempAdmin:temp" -sS 'http://localhost:3000/user/create?name=namePrivate&login=loginPrivate&password=private&make_news=true&admin=true'
у тебя во всех скриптах используется 3000 порт. Тогда либо меняй везде, либо убери это изменение

2023-06-27 03:57 UTC, pavelzarubin commented on stack.yaml.lock
> +    subdir: beam-postgres
тебе больше не нужен твой форк

2023-06-27 03:57 UTC, pavelzarubin commented on stack.yaml
> +  - beam-postgres
.

2023-06-27 03:57 UTC, pavelzarubin commented on src/Data/Utils.hs
> +    runInsertWithError,
лишнее

2023-06-27 04:12 UTC, pavelzarubin requested changes

2023-06-27 04:12 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      (const (throwIO $ err401 {errBody = "Login exist."}) . handler)
я что-то не понял, в чем суть такой обработки. Ошибку ты пробрасываешь, а логи будут? ты проверял?

2023-06-27 04:12 UTC, pavelzarubin commented on src/Data/Imp/Server/Authorization.hs
> +      Logger.logError logger $ "Exception: " <> (Data.Text.pack . show $ sqlState exc)
я это приводил в пример. Если ты словил ошибку, так и вывод лог об ошибке.

2023-06-27 04:13 UTC, pavelzarubin commented
Сервер повторно так и не запускается, так как первичный админ создается у тебя не внутри миграции.

2023-06-27 04:14 UTC, pavelzarubin commented on package.yaml
> +- postgresql-simple
эти пакеты точно задействованы?

2023-11-29 02:39 UTC, stepa1000 commented
> Сервер повторно так и не запускается, так как первичный админ создается у тебя не внутри миграции.

в beam-migrate отцутствует возможность ставки в таблицу значения во время миграции.

2023-11-29 03:08 UTC, stepa1000 commented on src/Data/Imp/Server/Authorization.hs
> +      (const (throwIO $ err401 {errBody = "Login exist."}) . handler)
handler - лог для сервера. ErrorBody - лог для клиента.

2023-12-08 08:30 UTC, paffel2 requested changes

2023-12-08 08:30 UTC, paffel2 commented on src/Data/Imp/Server.hs
> +  mvCatch <- liftIO (newEmptyMVar @ServerError)
зачем тебе mvar? почему ты не можешь просто взять и обработать исключение и выдать отправить ошибку в случае неудачи?

2023-12-08 08:31 UTC, paffel2 commented on test/AuthorizationSpec.hs
> -    (Right lUser) = $ stateExeT stateAuth $ do
что мешает сделать ` fromRight undefined $ `, ты же все равно моковые данные используешь

2023-12-08 08:51 UTC, stepa1000 commented on src/Data/Imp/Server.hs
> +  mvCatch <- liftIO (newEmptyMVar @ServerError)
я использую catch для того чтобы поймать ошибку. Еще ошибка возникает в имплементации, а для того чтобы servant коректно обработал, приходиться поднимать в Handler srvant-а.

2023-12-08 08:53 UTC, paffel2 commented on src/Data/Imp/Server.hs
> +  mvCatch <- liftIO (newEmptyMVar @ServerError)
а в чем проблема использовать `catches` ?

2023-12-09 06:50 UTC, paffel2 approved these changes

2023-12-11 09:37 UTC, merged