category checking at unique.
stepa1000/my-web-server pull request #17
Opened 2023-06-16 10:02 UTC by stepa1000

2023-06-19 09:27 UTC, pavelzarubin requested changes

2023-06-21 03:45 UTC, pavelzarubin requested changes

2023-06-21 03:45 UTC, pavelzarubin commented on src/Data/Imp/Migration.hs
> +                unique
Такая миграция не сработает, так как тогда в таблице появится колонка `category_name` с параметром `NOT NULL` и с пустыми значениями. Нужно только добавить ограничение `NOT NULL` без удаления `category_name`

2023-11-29 03:12 UTC, stepa1000 commented
Merge?

2023-12-07 07:13 UTC, paffel2 commented on src/Data/Imp/Server/Category.hs
> +  mvbool <- newMVar True
зачем тебе здесь Mvar?

2023-12-07 07:15 UTC, paffel2 commented on src/Data/Imp/Server/Category.hs
> +      (\sqlE -> putMVar mvbool False >> handler sqlE >> throwIO (err401 {errBody = "Login exist."}))
зачем? Почему login exists? Нельзя ошибку просто перехватить и выдать ответ пользователю, как с созданием пользователя?

2023-12-07 07:23 UTC, paffel2 commented on src/Data/Imp/Server/Category.hs
> +    else return ()
А зачем вообще хранить список категорий наследников? Лучше собирать их, когда это действительно нужно. К тому же тебе нужно собирать только родительские.

2023-12-07 07:24 UTC, paffel2 commented on stack.yaml.lock
> +    subdir: beam-postgres
Доделай исправление с пользователями и отребейзи эту ветку

2023-12-08 06:48 UTC, paffel2 commented on src/Data/Imp/Server/Category.hs
> +    else return ()
Ты уже хранишь информацию о потомках. У тебя буквально информация об отношениях дублируется в этих списках, которые только будут расти и тебе их приходится каждый раз переписывать. Собирай категории рекурсивно. Удали вообще списки наследников.

2023-12-08 08:43 UTC, stepa1000 commented on src/Data/Imp/Server/Category.hs
> +  mvbool <- newMVar True
для того чтоб ловить оброботку ошибок в catch.

2023-12-08 08:51 UTC, paffel2 commented on src/Data/Imp/Server/Category.hs
> +  mvbool <- newMVar True
так лови ее, а не тащи сюда императивщину

2023-12-14 05:05 UTC, stepa1000 commented on src/Data/Imp/Server/Category.hs
> +    else return ()
Сделал.

2023-12-14 05:05 UTC, stepa1000 commented on src/Data/Imp/Server/Category.hs
> +      (\sqlE -> putMVar mvbool False >> handler sqlE >> throwIO (err401 {errBody = "Login exist."}))
Сделал.

2023-12-14 05:05 UTC, stepa1000 commented on src/Data/Imp/Server/Category.hs
> +  mvbool <- newMVar True
Заменид на try.

2023-12-14 06:53 UTC, paffel2 requested changes
Нет проверки, что родительская категория существует. Ошибки о том, что категория уже существует, в ответе на запрос не возвращается.

2023-12-14 06:53 UTC, paffel2 commented on src/Data/Imp/Server/Category.hs
> +      lCategory <- Maybe.catMaybes <$> P.mapM (getNewsCategory logger connectDB) lNameCategory
По-хорошему здесь мы должны использовать рекурсивный запрос к БД. Но ладно можно оставить так, так как beam тебе не предоставляет возможности писать запросы самостоятельно.

2023-12-15 03:24 UTC, stepa1000 commented
> Нет проверки, что родительская категория существует. Ошибки о том, что категория уже существует, в ответе на запрос не возвращается.

имя категории должно быть уникальна, или  только ID категории уникально?

2023-12-15 06:00 UTC, paffel2 commented
> имя категории должно быть уникальна, или только ID категории уникально?

и то и другое

2023-12-15 09:07 UTC, stepa1000 commented
> > имя категории должно быть уникальна, или только ID категории уникально?
> 
> и то и другое

В миграциях так и есть.

2023-12-15 09:49 UTC, paffel2 commented
> > > имя категории должно быть уникальна, или только ID категории уникально?
> > 
> > 
> > и то и другое
> 
> В миграциях так и есть.

так сделай запрос, в котором создается категория, у которой родительская категория не существует. У тебя такая категория создается, в этом и ошибка.

2023-12-15 10:38 UTC, stepa1000 commented
> > > > имя категории должно быть уникальна, или только ID категории уникально?
> > > 
> > > 
> > > и то и другое
> > 
> > 
> > В миграциях так и есть.
> 
> так сделай запрос, в котором создается категория, у которой родительская категория не существует. У тебя такая категория создается, в этом и ошибка.

Сделал

2023-12-15 10:52 UTC, paffel2 commented on src/API/Server/Web.hs
> +      :> QueryParam' '[Strict] "root" Category
Так мы же должны иметь возможность, создавать категории без родительской, здесь не было ошибки. Просто сделай, чтобы General ставился по-умолчанию, либо вообще его убери, так как в нем нет надобности.

2023-12-15 11:57 UTC, stepa1000 commented on src/API/Server/Web.hs
> +      :> QueryParam' '[Strict] "root" Category
Убрал

2023-12-18 06:06 UTC, paffel2 commented on src/API/Server/Web.hs
> +      :> QueryParam' '[Strict] "root" Category
'http://localhost:5435/category/create?category_name=testCategory' -  запрос не проходит

2023-12-19 02:31 UTC, stepa1000 commented on src/API/Server/Web.hs
> +      :> QueryParam' '[Strict] "root" Category
Теперь использую General по умолчанию.

2023-12-20 10:46 UTC, paffel2 approved these changes

2023-12-23 03:48 UTC, merged