Polish
stepa1000/my-web-server pull request #18
Opened 2023-12-23 04:35 UTC by stepa1000

2023-12-24 05:46 UTC, paffel2 requested changes
В `Data.Instance` используй `{-# OPTIONS_GHC -Wno-orphans #-}`, чтобы варнинг отключить. 

https://github.com/stepa1000/my-web-server/blob/048e28a1dce0fd3af7a57b02776f828e6e9d2ff0/src/Control/Server.hs#L68

https://github.com/stepa1000/my-web-server/blob/048e28a1dce0fd3af7a57b02776f828e6e9d2ff0/src/Control/Server.hs#L115

Это лишнее вроде.

2023-12-24 05:46 UTC, paffel2 commented on README.md
> +run `stack build` and `stack exec my-web-server-exe`.
А где настройка БД?

2023-12-26 11:06 UTC, stepa1000 commented
> В `Data.Instance` используй `{-# OPTIONS_GHC -Wno-orphans #-}`, чтобы варнинг отключить.
> 
> https://github.com/stepa1000/my-web-server/blob/048e28a1dce0fd3af7a57b02776f828e6e9d2ff0/src/Control/Server.hs#L68
> 
> https://github.com/stepa1000/my-web-server/blob/048e28a1dce0fd3af7a57b02776f828e6e9d2ff0/src/Control/Server.hs#L115
> 
> Это лишнее вроде.
`
instance ToJSON ConnectInfo


instance FromJSON ConnectInfo
`
В `Data.Instance` требуют  `{-# OPTIONS_GHC -Wno-orphans #-}`, для того чтобы читать конфиги, а также использовать дженерики.

2023-12-26 12:38 UTC, paffel2 commented
> `instance ToJSON ConnectInfo` `instance FromJSON ConnectInfo` В `Data.Instance` требуют `{-# OPTIONS_GHC -Wno-orphans #-}`, для того чтобы читать конфиги, а также использовать дженерики.

так я понимаю, у тебя просто варнинг о том, что у тебя тут orphan пропадет, инстанс будет работать и дальше

2024-01-14 09:01 UTC, stepa1000 commented
/home/stepan/Haskell/my-web-server/src/Data/Instance.hs:7:1: error: [-Worphans, -Werror=orphans]
    Orphan instance: instance ToJSON ConnectInfo
    To avoid this
        move the instance declaration to the module of the class or of the type, or
        wrap the type with a newtype and declare the instance on the new type.
  |
7 | instance ToJSON ConnectInfo

Что мне надо ещё исправить?

2024-01-14 10:04 UTC, paffel2 commented
> /home/stepan/Haskell/my-web-server/src/Data/Instance.hs:7:1: error: [-Worphans, -Werror=orphans] Orphan instance: instance ToJSON ConnectInfo To avoid this move the instance declaration to the module of the class or of the type, or wrap the type with a newtype and declare the instance on the new type. | 7 | instance ToJSON ConnectInfo
> 
> Что мне надо ещё исправить?

ничего просто строчку добавить, чтобы варнинг при компиляции не появлялся

2024-01-24 13:44 UTC, paffel2 approved these changes

2024-01-25 05:25 UTC, merged