fix warnings
stepa1000/my-web-server pull request #9
Opened 2023-03-21 11:19 UTC by stepa1000

2023-03-22 07:42 UTC, pavelzarubin commented
у тебя много где такая прагма используется
```Haskell
{-# OPTIONS_GHC -Wwarn #-}
```

2023-03-28 08:18 UTC, stepa1000 commented
в имплементации новостей оброщения к БД имеют многоетажные типы, так что я решил  что четабельней чтоб ghc сам вывел.

2023-03-28 09:27 UTC, pavelzarubin commented
Ну так синонимы используй, не вижу в этом проблемы.

2023-03-29 08:40 UTC, stepa1000 commented
тип данных ConnectInfo из другого пакета, а надо обьявить инстанц для JSON. Инстанци реализуються сами, но получаеться Orphan instance. Прописывать ли вручную.

2023-03-29 08:49 UTC, pavelzarubin commented
ну я про orphans тебе в другом ишью писал, их нужно вынести в отдельный модуль и там этот варнинг заглушишь

2023-03-29 09:20 UTC, pavelzarubin requested changes

2023-03-29 09:20 UTC, pavelzarubin commented on src/Data/Imp/Server.hs
> +    m1 [News]
что мешает это заменить синонимами?

2023-03-29 09:40 UTC, pavelzarubin commented on src/Data/Imp/Server/News.hs
> +    Bool
Это можно каким-нибудь синонимом выразить для читабельности

2023-03-30 07:29 UTC, stepa1000 commented on src/Data/Imp/Server.hs
> +                      m2 NewsCategory
можно оставить текущее для типов с одним параметром?

2023-04-03 18:34 UTC, pavelzarubin approved these changes

2023-04-04 07:37 UTC, merged